- name: Install some python dependencies
  pip:
    name:
      - requests
      - influxdb
    state: present

- name: Start influxd
  service:
    name: influxd
    state: started

- name: Restart influxd
  service:
    name: influxd
    state: restarted


- name: Wait for a connection on influxdb port
  wait_for:
    host: localhost
    port: 8086

- name: Add admin user to influx
  influxdb_user:
    admin: yes
    user_name: "{{ influxdb_admin_user }}"
    user_password: "{{ influxdb_admin_user_password }}"
    state: present
